---
# tasks file for prov
- name: Create Data Center for Lab
  vmware_datacenter:
    hostname: "{{ prov_vc }}"
    username: "{{ prov_vcadmin }}"
    password: "{{ prov_vcpass }}"
    validate_certs: false
    datacenter_name: "{{ prov_dc }}"
  tags: ['dc']

- name: Create Cluster for Lab
  vmware_cluster:
    hostname: "{{ prov_vc }}"
    username: "{{ prov_vcadmin }}"
    password: "{{ prov_vcpass }}"
    validate_certs: false
    datacenter_name: "{{ prov_dc }}"
    cluster_name: "{{ prov_cluster }}"
  tags: ['cluster']
