---
# tasks file for vsphere
- name: Deploy ESX Guests from Templates
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vc }}"
    username: "{{ vsphere_vcadmin }}"
    password: "{{ vsphere_vcpass }}"
    validate_certs: false
    power_on_after_clone: false
    guest: "{{ item }}"
    from_template: yes
    template_src: "{{ vsphere_esx_template }}"
    cluster: "{{ vsphere_cluster }}"
    esxi:
      datacenter: "{{ vsphere_dc }}"
      hostname: "{{ vsphere_host }}"
  with_items: "{{ vsphere_esxlist }}"
  tags: ['clone']



- name: Update Memory and Network for  ESX Guests
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vc }}"
    username: "{{ vsphere_vcadmin }}"
    password: "{{ vsphere_vcpass }}"
    validate_certs: false
    cluster: "{{ vsphere_cluster }}"
    guest: "{{ item }}"
    state: reconfigured
    vm_hardware:
      memory_mb: "{{ vsphere_ram }}"
      num_cpus: "{{ vsphere_vcpu }}"
    esxi:
      datacenter: "{{ vsphere_dc }}"
      hostname: "{{ vsphere_host }}"
  with_items: "{{ vsphere_esxlist }}"
  tags: ['reconfigure']

