---
  - name: set /etc/localtime
    file: src=/usr/share/zoneinfo/{{common_timezone}} dest=/etc/localtime owner=root group=root state=link 
    when: common_timezone is defined
    tags: ['timezone']

  - name: set /etc/timezone
    template: src=templates/etc/timezone dest=/etc/timezone
    notify: update timezone
    when: common_timezone is defined
    tags: ['timezone']

